"""
Django settings for djangoProject15 project.

Generated by 'django-admin startproject' using Django 4.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os.path
from datetime import timedelta
from pathlib import Path
from django.contrib import messages
import os
from dotenv import load_dotenv
from django.middleware.cache import UpdateCacheMiddleware, FetchFromCacheMiddleware

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to off. The local stack sets DEBUG=True in .env so that
# SECURE_SSL_REDIRECT below does not bounce plain-HTTP test traffic to https.
DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 'yes')

# getenv returns None for anything unset, and a None in ALLOWED_HOSTS makes every
# host check raise rather than simply fail, so filter before assigning.
ALLOWED_HOSTS = [h for h in [
    '127.0.0.1',
    'localhost',
    'web',
    os.getenv('SERVER_URL'),
    os.getenv('SERVER_IP'),
] if h]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Alltechmanagement.apps.AlltechmanagementConfig',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'csp',
    'django_extensions',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    "django_permissions_policy.PermissionsPolicyMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]
PERMISSIONS_POLICY = {
    "accelerometer": [],
    "ambient-light-sensor": [],
    "autoplay": [],
    "camera": [],
    "display-capture": [],
    "document-domain": [],
    "encrypted-media": [],
    "fullscreen": [],
    "geolocation": [],
    "gyroscope": [],
    "interest-cohort": [],
    "magnetometer": [],
    "microphone": [],
    "midi": [],
    "payment": [],
    "usb": [],
}
WHITENOISE_MAX_AGE = 31536000  # 1 year in seconds
CORS_ALLOW_CREDENTIALS = True
# connect-src no longer includes a model provider: the AI runs server-side, so
# the browser never calls one. It previously did, with a token shipped in the
# bundle.
CONTENT_SECURITY_POLICY = {'DIRECTIVES': {'connect-src': tuple(
                                x for x in (
                                    "'self'",
                                    os.getenv('SUPABASE_URL'),
                                    'https://challenges.cloudflare.com',
                                ) if x),
                'default-src': ("'self'",),
                'font-src': ("'self'",),
                'form-action': ("'self'",),
                'frame-ancestors': ("'none'",),
                # Cloudflare Turnstile renders in an iframe and loads its own
                # script; without these the challenge silently fails to appear.
                'frame-src': ('https://challenges.cloudflare.com',),
                'img-src': ("'self'",),
                'object-src': ("'none'",),
                'script-src': ("'self'", 'https://challenges.cloudflare.com'),
                'style-src': ("'self'", "'unsafe-inline'")}}
ROOT_URLCONF = 'djangoProject15.urls'
CORS_ALLOWED_ORIGINS = [
    'https://pos.alltechnyeri.co.ke',
    'https://analytics.alltechnyeri.co.ke',
    'http://localhost:3000',
    'http://localhost:5173',

]
# HSTS settings
# SECURE_SSL_REDIRECT is separately switchable so a server can be brought up on a
# bare IP over HTTP before TLS is terminated in front of it, without the far worse
# workaround of turning DEBUG on in production. Turn it back on (drop the env var)
# the moment certificates are in place -- HSTS below is meaningless without it.
# TLS is terminated ahead of this process (Cloudflare at the edge, nginx at the
# origin), so the request arrives over plain HTTP and request.is_secure() is
# False unless Django is told how to recognise a forwarded HTTPS request.
# Without this, SECURE_SSL_REDIRECT below redirects to https, the proxy forwards
# the result back over http, and the browser loops until it gives up.
#
# Only safe because nothing reaches this process except through that proxy; a
# directly reachable origin would let a client forge the header. The origin must
# stay firewalled to the proxy.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

if not DEBUG:
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'True').lower() in ('true', '1', 'yes')
    # The health endpoint is exempt, and has to be. It is probed over plain
    # HTTP on localhost by the container healthcheck and by the deploy job,
    # neither of which goes through the proxy and so neither of which carries
    # X-Forwarded-Proto. Without this the probe gets a 301 to https on a port
    # that serves none, the container is marked unhealthy, and every deploy
    # fails while the service is in fact fine.
    SECURE_REDIRECT_EXEMPT = [r'^api/health/$']
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
    'OPTIONS'
]

WHITENOISE_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_HEADERS = [
    'content-type',
    'authorization',
    'X-CSRFToken',
]
CELERY_API_KEY = os.getenv('CELERY_KEY')
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangoProject15.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

RATELIMIT_IP_META_KEY = lambda request: request.META.get('HTTP_X_FORWARDED_FOR', '').split(',')[0] or request.META.get('REMOTE_ADDR')


# settings.py

# DB_SCHEMA confines every table this project owns to one Postgres schema. The
# Supabase instance is shared with other applications, so writing into `public`
# means competing for table names with them.
#
# The search path is deliberately the schema alone, with no `public` fallback.
# Including public would let Django resolve an existing public.django_migrations
# and conclude that migrations it has never applied here were already done.
DB_SCHEMA = os.getenv('DB_SCHEMA')
# Where Postgres extensions live. Appended to the search path so pg_trgm's
# functions resolve; never first, so tables still land in DB_SCHEMA. Supabase
# installs extensions into `public`.
DB_EXTENSIONS_SCHEMA = os.getenv('DB_EXTENSIONS_SCHEMA', 'public')

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'postgres'),
        'USER': os.getenv('DB_CRED'),
        'PASSWORD': os.getenv('DB_PASS'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}

if DB_SCHEMA:
    DATABASES['default'].setdefault('OPTIONS', {})
    _path = DB_SCHEMA
    if DB_EXTENSIONS_SCHEMA and DB_EXTENSIONS_SCHEMA != DB_SCHEMA:
        _path += f',{DB_EXTENSIONS_SCHEMA}'
    DATABASES['default']['OPTIONS']['options'] = f'-c search_path={_path}'

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv('REDIS_URL'),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "PASSWORD": os.getenv('REDIS_PASS'),
        },
        "KEY_PREFIX": "alltech_mgmt"
    }
}
# --- Supabase (identity) ---
SUPABASE_URL = os.getenv('SUPABASE_URL')
# Service role. Never expose this to a browser: it bypasses row-level security
# and can rewrite any user's app_metadata, including their role.
SUPABASE_KEY = os.getenv('SUPABASE_KEY')
# Shared HS256 secret from the Supabase dashboard (Settings -> API -> JWT
# Secret). When present, tokens are verified in-process. When absent, tokens are
# verified by asking Supabase, which is correct but adds a network round trip to
# cold requests -- see supabase_auth.py.
SUPABASE_JWT_SECRET = os.getenv('SUPABASE_JWT_SECRET')

# --- Passkeys (WebAuthn) ---
# The relying-party id is the site's registered domain (no scheme, no port) and
# the origin is the exact URL the browser reports. A mismatch in either makes
# every assertion fail with a message that does not say which one is wrong, so
# they are configuration rather than guesses derived from the request -- a
# request-derived value would also let a caller choose its own origin.
WEBAUTHN_RP_ID = os.getenv('WEBAUTHN_RP_ID')
WEBAUTHN_ORIGIN = os.getenv('WEBAUTHN_ORIGIN')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'Alltechmanagement.supabase_auth.SupabaseJWTAuthentication',
    ],
    # No endpoint is reachable without an Alltech role unless it opts out
    # explicitly. The previous default let any authenticated caller reach any
    # endpoint, and a forgotten decorator left it wide open rather than closed.
    'DEFAULT_PERMISSION_CLASSES': [
        'Alltechmanagement.permissions.IsAlltechUser',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',  # Only allow JSON responses
    ],

    'DEFAULT_THROTTLE_RATES': {

        'anon': '2/hour',
        'user': '4/minute',
        'pos_auth': '5/minute',
        'inventory_mod': '30/minute',
        'sales_ops': '120/minute',
        'order_mgmt': '60/minute',
        'inventory_check': '300/minute',
        'celery_auth_token': '5/day',
        'weekly_email': '5/day',
        'dashboard': '20/second',
    },
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
    'NUM_PROXIES': 1,
}

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True

# settings.py


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'Alltechmanagement/static')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
'''STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "Alltechmanagement/static"),
]'''
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}
KEY = os.path.join(BASE_DIR, 'key_pair.json')
# Containers log to stdout so `docker logs` and the platform's log collector can
# see them. Writing django.log into the working directory meant logs died with
# the container and were invisible to anything outside it. Set LOG_FILE to opt
# back into a file for local debugging.
LOG_FILE = os.getenv('LOG_FILE')
LOG_LEVEL = os.getenv('LOG_LEVEL', 'INFO')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': True,
        },
        'scheduler': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': True,
        },
    },
}

if LOG_FILE:
    LOGGING['handlers']['file'] = {
        'level': 'DEBUG',
        'class': 'logging.FileHandler',
        'filename': LOG_FILE,
        'formatter': 'verbose',
    }
    for _logger in LOGGING['loggers'].values():
        _logger['handlers'].append('file')
