# Generated by Django 6.1.1 on 2026-09-13 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alltechmanagement', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorizedFirebaseToken',
        ),
    ]
