# Generated by Django 4.2.8 on 2024-01-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alltechmanagement', '0002_completed_transactions_home_stock_saved_transactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantity', models.IntegerField()),
                ('customer_name', models.CharField(default='null', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='receiptsdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantity', models.IntegerField()),
                ('customer_name', models.CharField(default='null', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='completed_transactions',
            name='customer_name',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
