# Generated by Django 4.2.8 on 2024-02-15 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Alltechmanagement', '0003_receipts_receiptsdb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saved_transactions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
