# Generated by Django 6.1.1 on 2026-09-13 13:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alltechmanagement', '0004_trigram_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly')], db_index=True, max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'insights',
                'ordering': ['-created_at'],
            },
        ),
    ]
