# Generated by Django 4.2.8 on 2024-02-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alltechmanagement', '0006_completed_transactions2_saved_transactions2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale_summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('products_sold', models.IntegerField()),
            ],
        ),
    ]
