# Generated by Django 4.2.8 on 2024-02-19 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alltechmanagement', '0007_sale_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale_summary',
            name='products_sold',
        ),
    ]
