# Generated by Django 4.2.8 on 2024-02-19 06:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Alltechmanagement', '0008_remove_sale_summary_products_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale_summary',
            name='product_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
