# Generated by Django 4.2.8 on 2024-02-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alltechmanagement', '0009_sale_summary_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale_summary',
            name='total_goods',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale_summary',
            name='total',
            field=models.IntegerField(),
        ),
    ]
