# Generated by Django 4.2.8 on 2024-02-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alltechmanagement', '0011_remove_sale_summary_total_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale_summary',
            name='total_sold',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
