# Generated by Django 4.2.8 on 2024-02-19 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alltechmanagement', '0012_sale_summary_total_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale_summary',
            name='total_sold',
        ),
    ]
