# Generated by Django 4.2.8 on 2024-03-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alltechmanagement', '0017_shop_stock_fix_alter_shop2_stock_fix_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HOME_STOCK_FIX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30, unique=True)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
