# Generated by Django 4.2.8 on 2024-03-19 06:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Alltechmanagement', '0021_receipts2_fix_receipts_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipts2_fix',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
