# Generated by Django 4.2.8 on 2024-03-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alltechmanagement', '0022_receipts2_fix_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SALE_SUMMARY_FIX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField()),
                ('product_name', models.CharField(max_length=100)),
            ],
        ),
    ]
