# Generated by Django 4.2.8 on 2024-04-20 03:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Alltechmanagement', '0023_sale_summary_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipts_fix',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='receipts2_fix',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
