# Generated by Django 4.2.8 on 2024-08-18 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alltechmanagement', '0025_pushnotificationtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Completed_transactions',
        ),
        migrations.DeleteModel(
            name='Completed_transactions2',
        ),
        migrations.DeleteModel(
            name='Home_stock',
        ),
        migrations.DeleteModel(
            name='Receipts',
        ),
        migrations.DeleteModel(
            name='receiptsdb',
        ),
        migrations.DeleteModel(
            name='Sale_summary',
        ),
        migrations.DeleteModel(
            name='Saved_transactions',
        ),
        migrations.DeleteModel(
            name='Saved_transactions2',
        ),
        migrations.DeleteModel(
            name='Shop2_stock',
        ),
        migrations.DeleteModel(
            name='Shop_stock',
        ),
        migrations.DeleteModel(
            name='Shops_stock',
        ),
    ]
