# Generated by Django 4.2.8 on 2024-09-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alltechmanagement', '0026_delete_completed_transactions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedFirebaseToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
