# Generated by Django 4.2.8 on 2024-09-25 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alltechmanagement', '0027_authorizedfirebasetoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorizedfirebasetoken',
            name='created_at',
        ),
    ]
