# Generated by Django 4.2.8 on 2024-10-04 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alltechmanagement', '0029_webauthncredential'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebAuthnCredential',
        ),
    ]
