# Generated by Django 4.2.8 on 2024-10-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alltechmanagement', '0033_firebasewebauthncredential_delete_webauthncredential_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='FirebaseWebAuthnCredential',
        ),
        migrations.AddIndex(
            model_name='saved_transactions2_fix',
            index=models.Index(fields=['-created_at'], name='Alltechmana_created_1881d2_idx'),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
