# Generated by Django 5.1.3 on 2024-11-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alltechmanagement', '0035_delete_completed_transactions_fix_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LcdCustomers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutomer_name', models.CharField(max_length=255, unique=True)),
                ('total_spent', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
