# Generated by Django 5.1.3 on 2024-11-12 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alltechmanagement', '0036_lcdcustomers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lcdcustomers',
            old_name='cutomer_name',
            new_name='customer_name',
        ),
    ]
