# Generated by Django 5.1.3 on 2024-12-23 05:59

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alltechmanagement', '0038_alter_lcdcustomers_total_spent'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebAuthnCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_uid', models.CharField(db_index=True, help_text='Firebase User ID associated with this credential', max_length=128)),
                ('credential_id', models.CharField(help_text='Base64URL-encoded credential ID', max_length=255, unique=True)),
                ('credential_public_key', models.BinaryField(help_text='The credential public key in binary format')),
                ('sign_count', models.BigIntegerField(default=0, help_text='Number of times this credential has been used')),
                ('device_type', models.CharField(choices=[('platform', 'Platform'), ('cross-platform', 'Cross-Platform'), ('unknown', 'Unknown')], default='unknown', help_text='Type of authenticator device', max_length=32)),
                ('backed_up', models.BooleanField(help_text='Whether the credential is backed up', null=True)),
                ('transports', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='List of available transport methods')),
                ('device_name', models.CharField(blank=True, help_text='User-friendly name for the device', max_length=255)),
                ('device_info', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Additional device information')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the credential was first registered')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the credential was last updated')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='When the credential was last used for authentication', null=True)),
            ],
            options={
                'verbose_name': 'WebAuthn Credential',
                'verbose_name_plural': 'WebAuthn Credentials',
                'ordering': ['-last_used_at', '-created_at'],
                'indexes': [models.Index(fields=['firebase_uid', 'credential_id'], name='Alltechmana_firebas_3fe527_idx'), models.Index(fields=['last_used_at'], name='Alltechmana_last_us_d4016e_idx')],
            },
        ),
    ]
