# Generated by Django 5.1.3 on 2024-12-31 03:57

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alltechmanagement', '0039_webauthncredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='webauthncredential',
            name='aaguid',
            field=models.CharField(blank=True, help_text='Authenticator AAGUID', max_length=36),
        ),
        migrations.AddField(
            model_name='webauthncredential',
            name='attestation_object',
            field=models.BinaryField(blank=True, help_text='Raw attestation object from registration', null=True),
        ),
        migrations.AddField(
            model_name='webauthncredential',
            name='failed_attempts',
            field=models.IntegerField(default=0, help_text='Number of failed authentication attempts'),
        ),
        migrations.AddField(
            model_name='webauthncredential',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this credential is currently active'),
        ),
        migrations.AddField(
            model_name='webauthncredential',
            name='last_error',
            field=models.CharField(blank=True, help_text='Last error encountered with this credential', max_length=255),
        ),
        migrations.AlterField(
            model_name='webauthncredential',
            name='device_info',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Additional device information like platform, userAgent'),
        ),
        migrations.AlterField(
            model_name='webauthncredential',
            name='device_name',
            field=models.CharField(blank=True, help_text='User-friendly name for the device', max_length=64),
        ),
        migrations.AddIndex(
            model_name='webauthncredential',
            index=models.Index(fields=['is_active'], name='Alltechmana_is_acti_0427d0_idx'),
        ),
        migrations.AddIndex(
            model_name='webauthncredential',
            index=models.Index(fields=['failed_attempts'], name='Alltechmana_failed__0977d1_idx'),
        ),
    ]
