# Generated by Django 5.1.3 on 2025-01-10 08:06

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alltechmanagement', '0041_adminuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipts2_fix',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='receipts2_fix',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='receipts2_fix',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='receipts2_fix',
            name='customer_name',
            field=models.CharField(db_index=True, default='null', max_length=255),
        ),
        migrations.AlterField(
            model_name='receipts2_fix',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='receipts2_fix',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='receipts2_fix',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddIndex(
            model_name='receipts2_fix',
            index=models.Index(fields=['created_at', 'product_name'], name='Alltechmana_created_52b864_idx'),
        ),
        migrations.AddIndex(
            model_name='receipts2_fix',
            index=models.Index(fields=['created_at', 'customer_name'], name='Alltechmana_created_326ccd_idx'),
        ),
    ]
