# Generated by Django 5.1.3 on 2025-01-11 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alltechmanagement', '0042_alter_receipts2_fix_options_receipts2_fix_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='WebAuthnCredential',
        ),
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
