# Generated by Django 5.1.3 on 2025-01-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alltechmanagement', '0043_remove_adminuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completed_transactions2_fix',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='saved_transactions2_fix',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
    ]
