# Generated by Django 5.1.3 on 2025-01-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alltechmanagement', '0044_alter_completed_transactions2_fix_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop2_stock_fix',
            name='product_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
